### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#958]
Other Jupyter projects are transitionning to `main` as the default branch, for example in the JupyterHub org: https://github.com/jupyterhub/team-compass/issues/412

GitHub now makes it possible to do the rename from the GitHub UI directly:

![image](https://user-images.githubusercontent.com/591645/132856156-d8c1ac78-17e0-4d4e-ad51-614de511747f.png)

Existing PRs will target `main` automatically so it shouldn't be too much trouble to do the switch.

**Comment by jtpio** [comment]
ping @SylvainCorlay @maartenbreddels as organization owners with admin access on the repo (I do not have access to the settings).

> Existing PRs will target `main` automatically so it shouldn't be too much trouble to do the switch.

Given this and after doing it on a couple of other repos, we should be fine to proceed here too.

**Comment by jtpio** [comment]
## TODO

- [ ] Rename the master branch to main in GitHub (it will automatically update the open PRs)
- [ ] Update CI workflows 
- [ ] Update links
- [ ]  Update readthedocs default branch if needed

**Comment by jtpio** [comment]
>  Rename the master branch to main in GitHub (it will automatically update the open PRs)

You should get the following popup next time you visit the main page of the repo:

![image](https://user-images.githubusercontent.com/591645/133620525-f9470da4-8317-406f-9cfe-6b3aa930f937.png)

**Comment by jtpio** [comment]
>  Update readthedocs default branch if needed

Looks like there is nothing to do on the RTD side:

![image](https://user-images.githubusercontent.com/591645/133645267-45011d46-e178-46de-877c-c2234453f1c5.png)

**Comment by jtpio** [comment]
Closing as all items above have been addressed.
